// GET VIEWER
export const GET_VIEWER_PROCESS = "GET_VIEWER_PROCESS"
export const GET_VIEWER_SUCCESS = "GET_VIEWER_SUCCESS"
export const GET_VIEWER_ERROR = "GET_VIEWER_ERROR"

// POST VIEWER
export const POST_VIEWER_PROCESS = "POST_VIEWER_PROCESS"
export const POST_VIEWER_SUCCESS = "POST_VIEWER_SUCCESS"
export const POST_VIEWER_ERROR = "POST_VIEWER_ERROR"